[workspace]
members = [
  "holo-bfd",
  "holo-cli",
  "holo-daemon",
  "holo-interface",
  "holo-keychain",
  "holo-ldp",
  "holo-northbound",
  "holo-ospf",
  "holo-policy",
  "holo-protocol",
  "holo-rip",
  "holo-routing",
  "holo-tools",
  "holo-utils",
  "holo-yang",
]
default-members = ["holo-daemon", "holo-cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
authors = ["Renato Westphal <renatowestphal@gmail.com>"]
license = "MIT"
edition = "2021"

[workspace.dependencies]
async-trait = "0.1"
base64 = "0.21"
bitflags = { version = "2.4", features = ["serde"] }
bytes = { version = "1", features = ["serde"] }
capctl = "0.2"
check_keyword = "0.2"
clap = "2.33"
chrono = { version = "0.4", features = ["serde"] }
criterion = "0.4"
derive-new = "0.5"
enum-as-inner = "0.6"
futures = "0.3"
generational-arena = "0.2"
ipnetwork = "0.20"
hmac = "0.12"
itertools = "0.10"
libc = "0.2"
maplit = "1.0"
md5 = "0.7"
nix = "0.26"
netlink-packet-core = "0.7"
netlink-packet-route = "0.17"
netlink-sys = "0.8"
num-derive = "0.3"
num-traits = "0.2"
pickledb = "0.5"
prost = "0.12"
rand = "0.8.5"
rtnetlink = "0.13"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
sha1 = "0.10"
sha2 = "0.10"
similar = "2.0"
smallvec = { version = "1.11", features = ["serde"] }
socket2 = { version = "0.4", features = ["all"] }
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.10", features = ["tls"] }
tonic-build = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
yang2 = { version = "0.8", features = ["bundled"] }

[workspace.lints.rust]
rust_2018_idioms = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
too_many_arguments = "allow"

[profile.release]
lto = true
codegen-units = 1
