# User and group information
user = "frr"
group = "frr"

# Logging configuration
[logging]
  # Logging to journald
  [logging.journald]
    # Enable or disable
    enabled = false

  # Logging to a file
  [logging.file]
    # Enable or disable
    enabled = true
    # File path (needs to be writable by @user or @group)
    dir = "/var/log/"
    # File name
    name = "holod.log"
    # Log rotation (options: "never", "daily", "hourly")
    rotation = "never"
    # Logging style (options: "full", "compact", "pretty", "json")
    style = "full"
    # Enable or disable ANSI terminal colors
    colors = false
    # Sets whether or not the thread ID of the current thread is displayed
    show_thread_id = false
    # Sets whether or not an event’s source code file path and line number are displayed
    show_source = false

  # Logging to the standard output
  [logging.stdout]
    # Enable or disable
    enabled = false
    # Logging style (options: "full", "compact", "pretty", "json")
    style = "full"
    # Enable or disable ANSI terminal colors
    colors = false
    # Sets whether or not the thread ID of the current thread is displayed
    show_thread_id = false
    # Sets whether or not an event’s source code file path and line number are displayed
    show_source = false

# Instrumentation using tokio-console (a diagnostics and debugging tool)
[tokio_console]
  # Enable or disable
  enabled = false

# Event recorder (useful for bug reporting)
[event_recorder]
  # Enable or disable the event recorder
  enabled = false
  # Directory where to save the files (needs to be writable by @user or @group)
  dir = "/var/run/"

# Rollback log
#
# The rollback log provides the ability to revert to previous versions of the
# running configuration.
[rollback_log]
  # Enable or disable the rollback log
  enabled = true
  # Path to save the rollback log file (needs to be writable by @user or @group)
  path = "/var/run/holo.db"

# Daemon plugins
[plugins]
  # gRPC northbound plugin configuration
  [plugins.grpc]
    # Enable or disable the plugin
    enabled = true
    # gRPC server listening address
    address = "[::1]:50051"

  # gNMI northbound plugin configuration
  [plugins.gnmi]
    # Enable or disable the plugin
    enabled = true
    # gNMI server listening address
    address = "[::1]:10161"
    # Optional gNMI TLS configuration (should be disabled only for testing purposes)
    [plugins.gnmi.tls]
      # TLS certificate
      certificate = "/etc/tls/gnmi.pem"
      # TLS key
      key = "/etc/tls/gnmi.key"
