[package]
name = "holo-yang"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
maplit.workspace = true
serde.workspace = true
tracing.workspace = true
yang2.workspace = true

[lints]
workspace = true
